name: genezio workflow
on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: Genez-io/genezio-github-action@main
        with:
          token: ${{ secrets.GENEZIO_TOKEN }}
      - name: install pg
        working-directory: ./server
        run: npm install pg
      - name: preBackendDeploy
        working-directory: ./client
        run: npm install @genezio-sdk/crud-app_eu-central-1
      - name: preFrontendDeploy
        working-directory: ./client
        run: npm install
      - name: npm run build
        working-directory: ./client
        run: npm run build
      - name: Deploy backend
        run: genezio deploy
        env:
          CI: false